---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: '12'

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 8081, host: 8081}]
      - ["forwarded_port", {guest: 9081, host: 9081}]

#  - name: windows-2012r2
#    driver:
#      box: dhoer/windows-2012r2
#      network:
#      - ["forwarded_port", {guest: 8081, host: 8083}]

suites:
  - name: default
    run_list:
#      - nexus3_test::default
#      - nexus3_test::list_scripts
#      - nexus3_test::delete_script
      - nexus3_test::run_script
#      - nexus3_test::upload_script
#      - nexus3_test::script_content
      - nexus3_test::list_scripts
    attributes:
       nexus3:
         api:
           sensitive: false
           live_stream: false
